# Generated by Django 4.2.5 on 2023-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=101, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
