# Generated by Django 4.2.5 on 2023-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_id_alter_customer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
